import os
import json
from exa_py import Exa
from dotenv import load_dotenv # Import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Initialize the Exa client
# IMPORTANT: Replace 'YOUR_EXA_API_KEY' with your actual Exa API key.
# Consider using environment variables for better security.
exa_api_key = None # Initialize to None
exa = None # Initialize client to None
try:
    # You can set the EXA_API_KEY environment variable or replace the string below
    # exa_api_key = os.environ.get('EXA_API_KEY', 'c510befb-0169-444d-978a-53f8b5490a63')
    exa_api_key = os.getenv('EXA_API_KEY') # Get key from environment
    if not exa_api_key:
        print("Error: EXA_API_KEY not found in .env file or environment variables.")
    # if exa_api_key == 'YOUR_EXA_API_KEY':
    #     print("Warning: EXA_API_KEY is not set or using placeholder. Please replace 'YOUR_EXA_API_KEY'.")
    else:
        exa = Exa(exa_api_key) # Initialize client with the loaded key
        print("Exa Client initialized successfully.")
except Exception as e:
    print(f"Failed to initialize Exa Client: {e}")
    # exa = None # Keep exa as None if initialization failed

def exa_answer_search(company_name: str, company_address: str, system_prompt: str, user_prompt: str) -> dict | None:
    """
    Queries the Exa /answer endpoint.

    Args:
        company_name: The name of the company (used for logging/context).
        company_address: The address of the company (used for logging/context).
        system_prompt: The system prompt (not directly used by Exa /answer, but kept for consistency).
        user_prompt: The user prompt, which will be used as the query for Exa.

    Returns:
        A dictionary containing the response data in a format consistent
        with other API functions, or None if an error occurs.
    """
    if not exa:
        print("Exa client is not initialized. Cannot perform search.")
        return None

    print(f"Exa Answer Search for: {company_name}") # Indicate which function is running

    try:
        # Call the Exa answer endpoint using the user_prompt as the query
        # Setting text=True includes full text content in search results (citations)
        result = exa.answer(
            query=user_prompt,
            text=True,
            model='exa-pro' # Default model, uncomment to specify 'exa' or 'exa-pro'
        )

        # Print the raw response for debugging (optional)
        print("Raw Exa Response:")
        print(result)

        # Format the response to be consistent with other functions for Notion processing
        response_data = {
            "model": "exa_answer", # Identify the source model/API
            "choices": [
                {
                    "message": {
                        "role": "assistant",
                        "content": result.answer # The main answer text generated by Exa
                    }
                }
            ],
            "citations": [vars(citation) for citation in result.citations], # Include citations as extra info (converting Result object to dict)
            "usage": None # Exa answer endpoint doesn't provide token usage like OpenAI/Perplexity
            # You could potentially add cost if needed: "cost_dollars": result.cost_dollars
        }

        print("Formatted Exa Response Data for Notion:")
        print(json.dumps(response_data, indent=4)) # Pretty print the formatted data
        return response_data

    except Exception as e:
        print(f"Error calling Exa API for {company_name}: {e}")
        return None

# Example usage (can be commented out or removed when importing)
# if __name__ == "__main__":
#     test_company = "SpaceX"
#     test_address = "Rocket Road, Hawthorne, CA" # Fictional
#     test_user = "What is the latest valuation of SpaceX?"
#     api_result = exa_answer_search(test_company, test_address, test_system, test_user)
#     if api_result:
#         print("\n--- Final Result ---")
#         print(json.dumps(api_result, indent=4))
#     else:
#         print("API call failed.")
